spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./db.db
    username:
    password:
    #初始化的数据
    data: classpath:init-data.sql
    # Initialize the datasource with available DDL and DML scripts.
    initialization-mode: always
  jpa:
    database-platform: henryhui.site.study.data.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true

logging:
  config: classpath:logback-spring.xml
  file.path: ./logs