spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:H:\\sqlite\\db.db
    username:
    password:
  jpa:
    database-platform: henryhui.site.study.data.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true

logging:
  config: classpath:logback-spring.xml
  file.path: H:\\logs\\spring-boot-study