spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-boot-demo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
#    url: jdbc:mysql://192.168.55.7:3306/spring-boot-demo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: Root1234
    #初始化的数据
    data: classpath:init-data.sql
    # Initialize the datasource with available DDL and DML scripts.
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true

logging:
  config: classpath:logback-spring.xml
  file.path: ./logs


demo:
  login:
    salt: R3RpK750B8h84wm2
  auth:
    secret: dEm0
